### ISSUE TITLE
qmsk.backup-zfs --zfs-source can lose zfs incremental send bookmark on remote pool if zfs recv gets stuck

### ISSUE THREAD

**Issue by SpComb** [qmsk/backup#6]
The `qmsk.backup-zfs --zfs-source=...` option executes the equivalent of `ssh ... zfs send -i #X --bookmark=Y --purge-bookmark=X ... | zfs recv ...` to maintain the ZFS bookmark used for incremental sends on the source ZFS. The custom `qmsk.zfs-ssh-command` wrapper will perform the `zfs send`, and if it succeeds, create the new Y bookmark and destroy the old X bookmark.

If the `zfs recv` command on the backup machine gets stuck (due to e.g. https://github.com/openzfs/zfs/issues/11893), then the `zfs send` may still complete, but the snapshot data will be stuck in SSH/TCP/pipe buffers, and may never end up in the ZFS pool. The next time `qmsk.backup-zfs` runs, it will attempt to send from the old bookmark `X` corresponding to its last `X` snapshot, which no longer exists.

This means that incremental snapshot sends are no longer possible, and full send is required to sync up the backup pool again. The `qmsk.backup-zfs` command does not provide any option to force a full send, so the  backup dataset needs to be replaced using e.g. `zfs rename` and `qmsk.backup-zfs --setup-create` :confused: 

Workaround would be to add some `qmsk.backup-zfs --full-send` option to perform a full snapshot send, creating a new incremental send bookmark. This could possibly even happen automatically if the incremental send happens with a `incremental source (...) does not exist` error? Possibly the `zfs send` wrapper could even fallback to a full send if the incremental source is missing?

Fix would be to separate the `--purge-bookmark` operation into a separate step. It could probably be done during the next send-recv cycle - then there would generally be two bookmarks present on the source ZFS.

**Comment by SpComb** [comment]
Example failure:

The last snapshot on the backup ZFS is `...@20210423-070000`, but the bookmark on the source ZFS is `...#qmsk-backup:lemmikki:20210424-070000`, which corresponds with the `qmsk.backup-zfs` execution that got stuck on `zfs recv`.

```
+ set -ue
+ /opt/qmsk-backup/bin/qmsk.backup-zfs --zfs-source=... --zfs-raw --zfs-bookmark=qmsk-backup:lemmikki --ssh-identity=... ... --interval=10@recent:%Y%m%d-%H%M%S --interval=30@daily:%Y%m%d --purge
 WARNING          qmsk.invoke.stream: /usr/bin/ssh: Authorized uses only. All activity may be monitored and reported.
   ERROR qmsk.backup-ssh-command.main: Internal error: warning: cannot send '...@qmsk-backup_2021-04-30T04:00:01.592726': incremental source (...#qmsk-backup:lemmikki:20210423-070000) does not exist
Traceback (most recent call last):
  File "/opt/qmsk-backup/lib/python3.7/site-packages/qmsk/backup/zfs.py", line 33, in zfs
    stdout = invoker.invoke(ZFS, qmsk.invoke.optargs(*args), **opts)
  File "/opt/qmsk-backup/lib/python3.7/site-packages/qmsk/invoke.py", line 296, in invoke
    return invoke(cmd, args, sudo=self.sudo, **opts)
  File "/opt/qmsk-backup/lib/python3.7/site-packages/qmsk/invoke.py", line 128, in invoke
    raise InvokeError(cmd, p.returncode, stderr)
qmsk.invoke.InvokeError: /sbin/zfs failed (1): warning: cannot send '...@qmsk-backup_2021-04-30T04:00:01.592726': incremental source (...#qmsk-backup:lemmikki:20210423-070000) does not exist
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/qmsk-backup/bin/qmsk.zfs-ssh-command", line 259, in main
    return wrapper(command_parts[0], command_parts[1:])
  File "/opt/qmsk-backup/bin/qmsk.zfs-ssh-command", line 191, in __call__
    return self.zfs(args)
  File "/opt/qmsk-backup/bin/qmsk.zfs-ssh-command", line 178, in zfs
    return self.zfs_send(args)
  File "/opt/qmsk-backup/bin/qmsk.zfs-ssh-command", line 140, in zfs_send
    dedup               = args.dedup,
  File "/opt/qmsk-backup/lib/python3.7/site-packages/qmsk/backup/zfs.py", line 373, in send
    return self.filesystem.zfs_read('send', *self._send_options(**options), stdout=stdout)
  File "/opt/qmsk-backup/lib/python3.7/site-packages/qmsk/backup/zfs.py", line 112, in zfs_read
    return zfs(*args, invoker=self.invoker, **opts)
  File "/opt/qmsk-backup/lib/python3.7/site-packages/qmsk/backup/zfs.py", line 36, in zfs
    raise ZFSError(error.stderr)
qmsk.backup.zfs.ZFSError: warning: cannot send '...@qmsk-backup_2021-04-30T04:00:01.592726': incremental source (...#qmsk-backup:lemmikki:20210423-070000) does not exist
   ERROR      qmsk.backup-zfs.main: ...: cannot receive: failed to read from stream
Traceback (most recent call last):
  File "/opt/qmsk-backup/lib/python3.6/site-packages/qmsk/backup/zfs.py", line 33, in zfs
    stdout = invoker.invoke(ZFS, qmsk.invoke.optargs(*args), **opts)
  File "/opt/qmsk-backup/lib/python3.6/site-packages/qmsk/invoke.py", line 296, in invoke
    return invoke(cmd, args, sudo=self.sudo, **opts)
  File "/opt/qmsk-backup/lib/python3.6/site-packages/qmsk/invoke.py", line 128, in invoke
    raise InvokeError(cmd, p.returncode, stderr)
qmsk.invoke.InvokeError: /sbin/zfs failed (1): cannot receive: failed to read from stream
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/qmsk-backup/bin/qmsk.backup-zfs", line 483, in main
    create          = args.setup_create,
  File "/opt/qmsk-backup/bin/qmsk.backup-zfs", line 247, in backup
    snapshot = self.snapshot(now, create=create)
  File "/opt/qmsk-backup/bin/qmsk.backup-zfs", line 210, in snapshot
    stdin       = stream,
  File "/opt/qmsk-backup/lib/python3.6/site-packages/qmsk/backup/zfs.py", line 276, in receive
    *properties_options, target, stdin=stdin,
  File "/opt/qmsk-backup/lib/python3.6/site-packages/qmsk/backup/zfs.py", line 135, in zfs_write
    return zfs(*args, invoker=self.invoker, **opts)
  File "/opt/qmsk-backup/lib/python3.6/site-packages/qmsk/backup/zfs.py", line 36, in zfs
    raise ZFSError(error.stderr)
qmsk.backup.zfs.ZFSError: cannot receive: failed to read from stream
```

**Comment by SpComb** [comment]
A full filesystem send into a destination with pre-existing older snapshots does not work:
```
cannot receive new filesystem stream: destination has snapshots (eg. tank/...@20210801-073000)
must destroy them to overwrite it
```

Nor does sending from an older bookmark, that does not match the latest snapshot on the receiver:
```
cannot receive incremental stream: most recent snapshot of tank/... does not
match incremental source
```

Even a non-incremental `zfs send -R ... | zfs receive -F ...` seems to have the same restriction:

```
cannot receive new filesystem stream: destination has snapshots (eg. tank/...@20210801-073000)
must destroy them to overwrite it
```

As such, it doesn't seem like any kind of "full snapshot send" exists. The destination filesystem must instead be destroyed/renamed, and a new full filesystem send performed.

**Comment by SpComb** [comment]
Using `zfs receive -s` and `zfs send -t ...` with the `zfs get receive_resume_token ...` property may also help with this, depending on how the receiving pool behaves in the specific situation (e.g. https://github.com/openzfs/zfs/issues/11893 PANIC).
